""" A simple turtle program that moves the turtle randomly in the grid 

This program will perform a "random walk" by moving the turtle randomly in the grid.

Implement the random_walk function that will move the turtle randomly in the grid.

"""
import turtle
turtle.setup(600,600,0,0)               # Set the size of the window
MJ = turtle.Turtle()
MJ.shape('turtle')
MJ.speed(100000)                    # Set the shape of the turtle to a turtle

for i in range(1):
    MJ.right(180)
    MJ.forward(40)
    MJ.right(110)
    MJ.forward(100)
    MJ.right(75)
    MJ.forward(50)
    MJ.right(45)
    MJ.forward(45)
    MJ.right(80)
    MJ.forward(30)
    MJ.left(80)
    MJ.forward(43)
    MJ.right(180)
    MJ.forward(43)
    MJ.right(80)
    MJ.forward(30)
    MJ.left(80)
    MJ.forward(45)
    MJ.right(45)
    MJ.forward(85)
    MJ.right(150)
    MJ.forward(80)
    MJ.circle(10, 600)
    MJ.right(48)
    MJ.forward(80)
    MJ.left(45)
    MJ.forward(10)
    MJ.left(92)
    MJ.forward(90)
    MJ.right(90)
    MJ.forward(20)
    MJ.right(90)
    MJ.forward(90)
    MJ.right(91)
    MJ.forward(20)
    MJ.left(180)
    MJ.forward(35)
    MJ.left(92)
    MJ.forward(91)
    MJ.right(15)
    MJ.forward(100)
    MJ.left(110)
    MJ.forward(40)
    MJ.left(90)
    MJ.forward(10)
    MJ.left(90)
    MJ.forward(25)
    MJ.right(110)
    MJ.forward(75)
    MJ.right(75)
    MJ.forward(40)
    MJ.right(45)
    MJ.forward(30)
    MJ.right(85)
    MJ.forward(33)
    MJ.left(90)
    MJ.forward(55)
    MJ.left(88)
    MJ.forward(10)
    MJ.left(90)
    MJ.forward(43)
    MJ.right(83)
    MJ.forward(30)
    MJ.left(80)
    MJ.forward(40)

    turtle.exitonclick()